package com.realme.portdoctor;

import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class ReportGenerator {

    public static String generateReport(PortScanner scanner, List<FixEngine.Fix> fixes) {
        StringBuilder report = new StringBuilder();
        
        report.append("========================================\n");
        report.append("  PORT DOCTOR - Device Analysis Report\n");
        report.append("========================================\n\n");
        
        // Device Info
        report.append("DEVICE INFORMATION\n");
        report.append("------------------\n");
        report.append("Device: ").append(getBuildProp("ro.product.model", "Unknown")).append("\n");
        report.append("Manufacturer: ").append(getBuildProp("ro.product.manufacturer", "Unknown")).append("\n");
        report.append("ROM: ").append(getBuildProp("ro.build.display.id", "Unknown")).append("\n");
        report.append("Android: ").append(getBuildProp("ro.build.version.release", "Unknown")).append("\n");
        report.append("SDK: ").append(getBuildProp("ro.build.version.sdk", "Unknown")).append("\n");
        report.append("Kernel: ").append(getKernelVersion()).append("\n");
        report.append("Date: ").append(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date())).append("\n\n");
        
        // Scan Results
        report.append("SCAN RESULTS\n");
        report.append("------------\n\n");
        
        List<PortScanner.Issue> allIssues = scanner.getAllIssues();
        int detectedCount = 0;
        
        report.append("DETECTED ISSUES:\n");
        for (PortScanner.Issue issue : allIssues) {
            if (issue.detected) {
                detectedCount++;
                report.append("  [" + issue.severity + "] " + issue.name + "\n");
                report.append("     " + issue.description + "\n\n");
            }
        }
        
        report.append("PASSED CHECKS:\n");
        for (PortScanner.Issue issue : allIssues) {
            if (!issue.detected) {
                report.append("  OK " + issue.name + "\n");
            }
        }
        
        report.append("\nSummary: " + detectedCount + " issue(s) found, ")
            .append(allIssues.size() - detectedCount).append(" check(s) passed\n\n");
        
        // Hardware Info
        report.append("HARDWARE DETAILS\n");
        report.append("----------------\n");
        report.append(getHardwareInfo());
        report.append("\n");
        
        // Fixes Applied
        if (fixes != null && !fixes.isEmpty()) {
            report.append("APPLIED FIXES\n");
            report.append("-------------\n");
            for (int i = 0; i < fixes.size(); i++) {
                report.append(i + 1 + ". " + fixes.get(i).name + "\n");
                report.append("   " + fixes.get(i).description + "\n\n");
            }
        }
        
        // Raw Scan Log
        report.append("RAW SCAN LOG\n");
        report.append("------------\n");
        report.append(scanner.getScanLog());
        report.append("\n");
        
        report.append("========================================\n");
        report.append("  Report generated by Port Doctor v1.0\n");
        report.append("========================================\n");
        
        return report.toString();
    }
    
    private static String getBuildProp(String key, String defaultVal) {
        try {
            Process p = Runtime.getRuntime().exec("getprop " + key);
            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String val = br.readLine();
            br.close();
            return val != null ? val.trim() : defaultVal;
        } catch (Exception e) {
            return defaultVal;
        }
    }
    
    private static String getKernelVersion() {
        try {
            BufferedReader br = new BufferedReader(new FileReader("/proc/version"));
            String version = br.readLine();
            br.close();
            return version != null ? version.trim() : "Unknown";
        } catch (Exception e) {
            return "Unknown";
        }
    }
    
    private static String getHardwareInfo() {
        StringBuilder hw = new StringBuilder();
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("/proc/cpuinfo"));
            String line;
            while ((line = br.readLine()) != null) {
                if (line.contains("Hardware") || line.contains("Processor")) {
                    hw.append("CPU: ").append(line.substring(line.indexOf(":") + 1).trim()).append("\n");
                }
            }
            br.close();
        } catch (Exception ignored) {}
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("/proc/meminfo"));
            String line = br.readLine();
            if (line != null) {
                hw.append("RAM: ").append(line.substring(line.indexOf(":") + 1).trim()).append("\n");
            }
            br.close();
        } catch (Exception ignored) {}
        
        try {
            Process p = Runtime.getRuntime().exec("wm size");
            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String size = br.readLine();
            if (size != null) hw.append("Display: ").append(size.trim()).append("\n");
            br.close();
        } catch (Exception ignored) {}
        
        try {
            File blDir = new File("/sys/class/backlight/");
            File[] panels = blDir.listFiles();
            if (panels != null && panels.length > 0) {
                String maxPath = panels[0].getAbsolutePath() + "/max_brightness";
                BufferedReader br = new BufferedReader(new FileReader(maxPath));
                hw.append("Panel Max Brightness: ").append(br.readLine().trim()).append("\n");
                br.close();
            }
        } catch (Exception ignored) {}
        
        return hw.toString();
    }
    
    public static File saveReport(String report, String path) throws IOException {
        File reportFile = new File(path);
        FileWriter fw = new FileWriter(reportFile);
        fw.write(report);
        fw.close();
        return reportFile;
    }
              }
